# Site settings
title: Longplay
subtitle: Album player for iOS and visionOS
logo: /images/longplay/icon.png

author:
  name: Adrian Schönig
  email: adrian@schoenig.me
copyright: |
  © 2020-2024 [Adrian Schönig](https://adrian.schoenig.me/).

  Powered by [Jekyll](https://jekyllrb.com) & [GitHub](https://github.com). Theme based on [So Simple](https://github.com/mmistakes/so-simple-theme). [Stats](https://longplay.goatcounter.com) powered by [GoatCounter](https://www.goatcounter.com).
description: >
  Longplay is the iOS and visionOS app for music lovers who enjoy listening to full albums but have a hard time finding them in their music library. It provides a beautiful view of the album artworks of the (near) complete albums in your music library with one-tap access to play them.
baseurl: ""
url: "https://longplay.rocks"
timezone: Australia/Sydney
encoding: UTF-8

appstore_id: 1495152002

mastodon:
  username: longplay
  instance: indieapps.space

goatcounter: longplay

# Regular posts
markdown: kramdown
excerpt_separator: <!--more-->

permalink: pretty

# Jekyll-seo-tag
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
locale: en_AU

include:
  - ".well-known"

collections:
  posts:
    output: true
    permalink: "/blog/:year/:title/"
  microposts:
    output: true
    permalink: /micro/:year/:month/:name.html
  collections:
    output: true
    sort_by: id

defaults:
  - scope:
      path: ""
      type: microposts
    values:
      layout: micro

pagination:
  enabled: true
  sort_reverse: true
  permalink: "/page/:num/"

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-twitter-plugin
  - jekyll/mastodon_webfinger
